file=open("example.txt",'w')
file.write('Never gonna give you up \n')
file.write('Never gonna let you down \n')
file.write('Never gonna run around and desert you \n')
file.write('Never gonna make you cry \n')
file.write('Never gonna say goodbye \n')
file.write('Never gonna tell a lie and hurt you \n')
file.write('We\'ve known each other for so long \n')
file.write('Your heart\'s been aching, but you\'re too shy to say it \n')
file.write('Inside, we both know what\'s been going on \n')
file.write('We know the game and we\'re gonna play it \n')
file.close()